site_name: Performance Achievement - Chand
nav:
  - Home: index.md
  - Key Achievements: achievements.md
  - Skills Development: skills.md
theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'blue'



